receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
#    drop in favor of jagger one
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - zipkin
        - jaeger