name: Check Contribution Terms Agreement

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Contribution Agreement
        uses: actions/github-script@v3
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            if (!prBody.includes("[X] I have read and agree to the contribution terms outlined in [CONTRIBUTING.md](https://github.com/ecotoneframework/ecotone-dev/blob/main/CONTRIBUTING.md)")) {
              core.setFailed("Contributor has not agreed to the contribution terms. Please provide set X in the checkbox to agree to the terms. `[X] I have read and agree to the contribution terms outlined in [CONTRIBUTING.md](https://github.com/ecotoneframework/ecotone-dev/blob/main/CONTRIBUTING.md)`");
          }
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Check for Contribution Files
        shell: bash
        run: |
          php bin/check-files.php